# Generated by Django 5.1.3 on 2024-11-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morelecturepdf',
            name='pdf_file',
            field=models.FileField(upload_to='more_lectures/'),
        ),
    ]
