# Generated by Django 5.1.3 on 2024-11-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_morelecturepdf_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morelecturepdf',
            name='pdf_file',
            field=models.FileField(upload_to='lectures/pdfs/'),
        ),
    ]
