# Generated by Django 5.1.3 on 2024-11-15 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturepdf',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
