# Generated by Django 5.1.3 on 2024-11-16 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_lecturepdf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturevideo',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
